---
# vars file for deploy-amazon-proxy-instances

instance_type: t2.medium
wait_time: 1
openvpn_proxy:
  - proxy01
  - proxy02
private_ip:
  - 'YOUR PRIVATE IP OF FIRST PROXY'
  - 'YOUR PRIVATE IP OF SECOND PROXY'
